services:
    directus:
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        env_file: .env
        environment:
            SECRET: ${SECRET}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            DB_CLIENT: ${DB_CLIENT}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}
            STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
            STORAGE_SUPABASE_DRIVER: ${STORAGE_SUPABASE_DRIVER}
            STORAGE_SUPABASE_SERVICE_ROLE: ${STORAGE_SUPABASE_SERVICE_ROLE}
            STORAGE_SUPABASE_BUCKET: ${STORAGE_SUPABASE_BUCKET}
            STORAGE_SUPABASE_PROJECT_ID: ${STORAGE_SUPABASE_PROJECT_ID}
